version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    container_name: foundryvtt
    restart: unless-stopped
    volumes:
      - foundry_data:/data
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_PASSWORD}
      - FOUNDRY_HOSTNAME=dnd.jck.sh
      - FOUNDRY_PORT=30000
    ports:
      - "30000:30000"
    networks:
      - internal

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - internal
      - external
    ports:
      - "80:80"
      - "443:443"

volumes:
  foundry_data:
  caddy_data:
  caddy_config:

networks:
  internal:
    internal: true
  external:
    driver: bridge
