services:

  rails_app:
    build:
      context: ./jck.sh
      dockerfile: Dockerfile
    container_name: rails_app
    restart: unless-stopped
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: rails_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - bundle_data:/usr/local/bundle
      - ./jck.sh:/jck.sh

  db:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rails_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  bundle_data:
  db_data:

