name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: git pull origin main

      - name: Build Dockerfile
        run: docker compose build

      - name: Restart Docker containers
        run: |
          docker compose down
          docker compose up -d --build
          

      - name: Health Check
        run: |
          echo "Waiting for service to be healthy..."
          for i in {1..10}; do
            if curl -fsSL https://jck.sh/up; then
              echo "Service is up!"
              exit 0
            fi
            echo "Waiting for service to start... ($i/10)"
            sleep 5
          done
          echo "Service did not start in time."
          exit 1
